# Generated by Django 5.2.15 on 2026-07-08 23:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('upwork_profile_url', models.URLField(blank=True, max_length=300)),
                ('upwork_profile_name', models.CharField(blank=True, max_length=150)),
                ('hourly_rate_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Hourly rate from client (USD)')),
                ('client_joined_date', models.DateField(blank=True, null=True, verbose_name='Date of joining the client')),
                ('entries_required', models.PositiveIntegerField(default=0, verbose_name='Number of entries to do')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ManyToManyField(blank=True, limit_choices_to={'role': 'employee'}, related_name='assigned_projects', to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ForeignKey(limit_choices_to={'role__in': ['pm', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_time_logs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='projects.project')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
