# Generated by Django 5.2.15 on 2026-07-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='billing_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('fixed', 'Fixed Price')], default='hourly', max_length=10, verbose_name='Project type'),
        ),
        migrations.AddField(
            model_name='project',
            name='fixed_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Fixed price (USD)'),
        ),
    ]
