# Generated by Django 5.2.7 on 2025-12-31 17:38

import accounts.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('cnic', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='CNIC must be exactly 13 digits.', regex='^\\d{13}$')])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Enter a valid email.')])),
                ('full_name', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.RegexValidator(message='Only alphabets and spaces are allowed.', regex='^[A-Za-z ]+$')])),
                ('fathers_name', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.RegexValidator(message='Only alphabets and spaces are allowed.', regex='^[A-Za-z ]+$')])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('na', 'Prefer not to say')], max_length=10, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=14, null=True)),
                ('residential_address', models.TextField(blank=True, max_length=250, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('reporting_manager_name', models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.RegexValidator(message='Only alphabets and spaces are allowed.', regex='^[A-Za-z ]+$')])),
                ('department', models.CharField(blank=True, choices=[('HR', 'HR'), ('IT', 'IT'), ('FIN', 'Finance'), ('OPS', 'Operations'), ('SALES', 'Sales'), ('OTHER', 'Other')], max_length=10, null=True)),
                ('designation', models.CharField(blank=True, max_length=120, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('CT', 'Contract'), ('IN', 'Internship')], max_length=2, null=True)),
                ('employee_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=accounts.models.profile_picture_path)),
                ('cnic_front', models.ImageField(blank=True, null=True, upload_to=accounts.models.cnic_front_path)),
                ('cnic_back', models.ImageField(blank=True, null=True, upload_to=accounts.models.cnic_back_path)),
                ('degree_certificate', models.FileField(blank=True, null=True, upload_to=accounts.models.degree_path)),
                ('father_cnic', models.ImageField(blank=True, null=True, upload_to=accounts.models.father_cnic_path)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=120, null=True)),
                ('emergency_relationship', models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('spouse', 'Spouse'), ('sibling', 'Sibling'), ('friend', 'Friend'), ('other', 'Other')], max_length=10, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=14, null=True)),
                ('emergency_contact_address', models.TextField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3, null=True)),
                ('previous_employer', models.TextField(blank=True, null=True)),
                ('special_skills', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('employee', 'Employee'), ('pm', 'Project Manager'), ('admin', 'Admin (CEO)')], default='employee', help_text="Role of the employee. Default is 'Employee'.", max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.EmployeeManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_entry_id', models.PositiveIntegerField(unique=True)),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField(blank=True)),
                ('action_time', models.DateTimeField()),
                ('url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-action_time'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_reset_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('members', models.ManyToManyField(blank=True, limit_choices_to={'role': 'employee'}, related_name='teams', to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ForeignKey(limit_choices_to={'role': 'pm'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
