# Generated by Django 5.2.15 on 2026-07-13 22:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpworkSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connect_rate', models.DecimalField(decimal_places=4, default=Decimal('0.15'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Upwork Setting',
                'verbose_name_plural': 'Upwork Settings',
            },
        ),
        migrations.CreateModel(
            name='UpworkProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_manager', models.ForeignKey(limit_choices_to={'role': 'pm'}, on_delete=django.db.models.deletion.CASCADE, related_name='upwork_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UpworkJobEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('jobs_applied', models.PositiveIntegerField(default=0)),
                ('proposal_views', models.PositiveIntegerField(default=0)),
                ('responses', models.PositiveIntegerField(default=0)),
                ('offers', models.PositiveIntegerField(default=0)),
                ('hired', models.PositiveIntegerField(default=0)),
                ('connects_used', models.PositiveIntegerField(default=0)),
                ('connect_rate', models.DecimalField(decimal_places=4, default=Decimal('0.15'), max_digits=8)),
                ('amount_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upwork_entries_created', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='upwork.upworkprofile')),
            ],
            options={
                'verbose_name': 'Upwork Job Entry',
                'verbose_name_plural': 'Upwork Job Entries',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('profile', 'date'), name='unique_profile_date_entry')],
            },
        ),
    ]
