# Generated by Django 5.2.15 on 2026-07-13 22:48

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upworkjobentry',
            name='connect_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('30.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='upworksetting',
            name='connect_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('30.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
