# Generated by Django 5.2.7 on 2025-12-31 17:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_to_pkr_rate', models.DecimalField(decimal_places=4, default=280.0, help_text='How many PKR in 1 USD (e.g., 277.0000).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ADVANCE', 'Advance Taken'), ('UPWORK_CONNECTS', 'Upwork Connects'), ('UPWORK_JOB', 'Paid Upwork Jobs'), ('OTHER', 'Other Expense')], default='OTHER', max_length=32)),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount_pkr', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PMResponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('pm', models.OneToOneField(limit_choices_to={'role': 'pm'}, on_delete=django.db.models.deletion.CASCADE, related_name='responsibility_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount_pkr', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=14)),
                ('admin_share_usd', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
                ('pm_share_usd', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
                ('date_paid', models.DateField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_salary_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_paid', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_month', models.DateField(default='2024-01-01')),
                ('effective_from', models.DateField()),
                ('monthly_salary_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('monthly_salary_pkr', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=14)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_profiles', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_employee_salaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Monthly Salary',
                'verbose_name_plural': 'Employee Monthly Salaries',
                'ordering': ['-salary_month', '-id'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'salary_month'), name='uniq_employee_salary_month')],
            },
        ),
        migrations.CreateModel(
            name='PMSalaryShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_percentage', models.DecimalField(decimal_places=2, default=50.0, help_text='Percentage of salary responsibility for this PM (0-100%).', max_digits=5)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('pm', models.ForeignKey(limit_choices_to={'role': 'pm'}, on_delete=django.db.models.deletion.CASCADE, related_name='salary_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('pm',)},
            },
        ),
    ]
