# Generated by Django 5.2.7 on 2026-02-01 12:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PMAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_type', models.CharField(choices=[('upwork_job_paid', 'Upwork job paid'), ('upwork_connects', 'Upwork connects'), ('cash_taken', 'Cash taken'), ('online_taken', 'Online taken')], max_length=30)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate_usd_to_pkr', models.DecimalField(decimal_places=2, default=Decimal('280.00'), max_digits=10)),
                ('advance_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pm_advances', to=settings.AUTH_USER_MODEL)),
                ('pm', models.ForeignKey(limit_choices_to={'role': 'pm'}, on_delete=django.db.models.deletion.CASCADE, related_name='pm_advances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-advance_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PMIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('upwork', 'Upwork')], default='upwork', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rate_usd_to_pkr', models.DecimalField(decimal_places=2, default=Decimal('280.00'), max_digits=10)),
                ('pm_share_percent', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('income_date', models.DateField(default=django.utils.timezone.localdate)),
                ('withdrawn_by_ceo', models.BooleanField(default=True)),
                ('withdrawn_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pm_incomes', to=settings.AUTH_USER_MODEL)),
                ('pm', models.ForeignKey(limit_choices_to={'role': 'pm'}, on_delete=django.db.models.deletion.CASCADE, related_name='pm_incomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-income_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PMSplitSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm_share_percent', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pm', models.OneToOneField(limit_choices_to={'role': 'pm'}, on_delete=django.db.models.deletion.CASCADE, related_name='pm_split_setting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PM Split Setting',
                'verbose_name_plural': 'PM Split Settings',
            },
        ),
    ]
