# Generated by Django 5.2.7 on 2026-02-01 13:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollGlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_to_pkr_rate', models.DecimalField(decimal_places=2, default=Decimal('280.00'), max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payroll Global Setting',
                'verbose_name_plural': 'Payroll Global Settings',
            },
        ),
    ]
