# Generated by Django 5.2.7 on 2026-02-01 13:11

from decimal import Decimal
from django.db import migrations, models


def forwards_copy_amount(apps, schema_editor):
    PMAdvance = apps.get_model("payroll", "PMAdvance")
    for adv in PMAdvance.objects.all():
        amount_usd = adv.amount_usd or Decimal("0.00")
        rate = adv.rate_usd_to_pkr or Decimal("0.00")
        adv.amount_pkr = amount_usd * rate
        adv.save(update_fields=["amount_pkr"])


def backwards_copy_amount(apps, schema_editor):
    PMAdvance = apps.get_model("payroll", "PMAdvance")
    for adv in PMAdvance.objects.all():
        amount_pkr = adv.amount_pkr or Decimal("0.00")
        rate = adv.rate_usd_to_pkr or Decimal("0.00")
        if rate:
            adv.amount_usd = amount_pkr / rate
        else:
            adv.amount_usd = Decimal("0.00")
        adv.save(update_fields=["amount_usd"])


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_payrollglobalsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmadvance',
            name='amount_pkr',
            field=models.DecimalField(decimal_places=2, max_digits=14, null=True, blank=True),
        ),
        migrations.RunPython(forwards_copy_amount, backwards_copy_amount),
        migrations.RemoveField(
            model_name='pmadvance',
            name='amount_usd',
        ),
        migrations.RemoveField(
            model_name='pmadvance',
            name='rate_usd_to_pkr',
        ),
        migrations.AlterField(
            model_name='pmadvance',
            name='amount_pkr',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
    ]
