# Generated by Django 5.2.7 on 2026-03-14 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_branch_fixedexpense_branchexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedexpense',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixed_expenses', to='payroll.branch'),
        ),
        migrations.AlterField(
            model_name='fixedexpense',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='fixedexpense',
            unique_together={('branch', 'name')},
        ),
    ]
