# Generated by Django 5.2.7 on 2026-03-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_fixedexpense_branch_alter_fixedexpense_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedexpense',
            name='expense_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('other', 'Other expense')], default='fixed', max_length=10),
        ),
    ]
