# Generated by Django 5.2.7 on 2026-03-14 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_alter_branchexpense_paid_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchexpense',
            name='paid_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['pm', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_expenses_paid', to=settings.AUTH_USER_MODEL),
        ),
    ]
