# Generated by Django 5.2.7 on 2026-03-14 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_alter_branchexpense_paid_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pmadvance',
            name='paid_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['pm', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_advances_paid_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pmincome',
            name='withdrawn_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['pm', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pm_income_withdrawn_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
