# Generated by Django 5.2.7 on 2026-03-14 22:04

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_pmadvance_paid_by_pmincome_withdrawn_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_type', models.CharField(choices=[('fixed_budget', 'Fix Budget'), ('timer', 'Timer')], max_length=20)),
                ('upwork_profile_name', models.CharField(max_length=150)),
                ('project_name', models.CharField(max_length=150)),
                ('entries_email', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('per_entry_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('number_of_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('per_hour_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('work_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['pm', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employee_salary_records', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to=settings.AUTH_USER_MODEL)),
                ('pm', models.ForeignKey(limit_choices_to={'role': 'pm'}, on_delete=django.db.models.deletion.CASCADE, related_name='employee_salary_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_pm_employee_salary',
                'ordering': ['-work_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('mess_hostel', 'Mess + Hostel Expenses'), ('advance_taken', 'Advance taken'), ('other', 'Other expenses')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('amount_pkr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('paid_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['pm', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employee_salary_expenses', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='salary_expenses', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['pm', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_salary_expenses_paid_by', to=settings.AUTH_USER_MODEL)),
                ('pm', models.ForeignKey(limit_choices_to={'role': 'pm'}, on_delete=django.db.models.deletion.CASCADE, related_name='employee_salary_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_pm_employee_salary_expense',
                'ordering': ['-paid_date', '-created_at'],
            },
        ),
    ]
