# Generated by Django 5.2.7 on 2026-03-14 22:34

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_employeesalary_employeesalaryexpense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalaryexpense',
            name='expense_type',
            field=models.CharField(choices=[('mess_hostel', 'Mess + Hostel Expenses'), ('advance_taken', 'Advance taken'), ('fines', 'Fines'), ('other', 'Other expenses')], max_length=20),
        ),
        migrations.CreateModel(
            name='EmployeeSalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_pkr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('paid_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['pm', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employee_salary_payments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(limit_choices_to={'role': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['pm', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_salary_paid_by', to=settings.AUTH_USER_MODEL)),
                ('pm', models.ForeignKey(limit_choices_to={'role': 'pm'}, on_delete=django.db.models.deletion.CASCADE, related_name='employee_salary_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_pm_employee_salary_payment',
                'ordering': ['-paid_date', '-created_at'],
            },
        ),
    ]
